CONDITIONS = {
    'Artery': 1,
    'Feedr': 2,
    'Norm': 3,
    'RRNn': 4,
    'RRAn': 5,
    'PosN': 6,
    'PosA': 7,
    'RRNe': 8,
    'RRAe': 9,
}

conversions = {
    'MSZoning': {
        'A': 1,
        'C (all)': 2,
        'FV': 3,
        'I': 4,
        'RH': 5,
        'RL': 6,
        'RP': 7,
        'RM': 8,
    },
    'Street': {
        'Grvl': 1,
        'Pave': 2,
    },
    'LotShape': {
        'Reg': 1,
        'IR1': 2,
        'IR2': 3,
        'IR3': 4,
    },
    'LandContour': {
        'Lvl': 1,
        'Bnk': 2,
        'HLS': 3,
        'Low': 4,
    },
    'Utilities': {
        'AllPub': 1,
        'NoSewr': 2,
        'NoSeWa': 3,
        'ELO': 4,
    },
    'LotConfig': {
        'Inside': 1,
        'Corner': 2,
        'CulDSac': 3,
        'FR2': 4,
        'FR3': 5,
    },
    'LandSlope': {
        'Gtl': 1,
        'Mod': 2,
        'Sev': 3,
    },
    'Neighborhood': {
        'Blmngtn': 1,
        'Blueste': 2,
        'BrDale': 3,
        'BrkSide': 4,
        'ClearCr': 5,
        'CollgCr': 6,
        'Crawfor': 7,
        'Edwards': 8,
        'Gilbert': 9,
        'IDOTRR': 10,
        'MeadowV': 11,
        'Mitchel': 12,
        'NAmes': 13,
        'NoRidge': 14,
        'NPkVill': 15,
        'NridgHt': 16,
        'NWAmes': 17,
        'OldTown': 18,
        'SWISU': 19,
        'Sawyer': 20,
        'SawyerW': 21,
        'Somerst': 22,
        'StoneBr': 23,
        'Timber': 24,
        'Veenker': 25,
    },
    'Condition1': CONDITIONS,
    'Condition2': CONDITIONS,
    'BldgType': {
        '1Fam': 1,
        '2fmCon': 2,
        'Duplex': 3,
        'TwnhsE': 4,
        'Twnhs': 5,
    },
}
